version: "3.8"
services:

    # PHP service
    app:
        build: .
        container_name: php-app
        working_dir: /var/www/
        volumes:
            - .:/var/www
        networks:
            - app-network

    # MySQL database service
    db:
        image: mysql:5.7
        container_name: mysql-db
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        env_file:
            - .env
        networks:
            - app-network

    # Nginx service
    nginx:
        image: nginx:alpine
        container_name: php-nginx
        ports:
            - 8000:80
        volumes:
            - .:/var/www
            - ./nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - app-network

    phpmyadmin:
        image: library/phpmyadmin
        container_name: php-phpmyadmin
        tty: true
        networks:
            - app-network
        depends_on:
            - db
        environment:
            PMA_USER: root
            PMA_PASSWORD: root
            PMA_HOSTS: db
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
        ports:
            - "8080:80"

networks:
    app-network:
        driver: bridge
